const id = (value: string | number) => encodeURIComponent(String(value));
// Paths are relative to EXPO_PUBLIC_API_URL, including /api.
export const endpoints = {
  auth: { login: '/auth/login', register: '/auth/register', forgotPassword: '/auth/forgot-password', resetPassword: '/auth/reset-password', profile: '/perfil', password: '/perfil/senha' },
  epis: '/epis',
  searchEpis: (nrRegistroCa: string) => `/epis?nr_registro_ca=${encodeURIComponent(nrRegistroCa.trim())}`,
  functions: '/funcoes',
  jobFunction: (value: number) => `/funcoes/${id(value)}`,
  workers: '/trabalhadores',
  suppliers: '/fornecedores',
  supplier: (value: number) => `/fornecedores/${id(value)}`,
  worker: (value: number) => `/trabalhadores/${id(value)}`,
  purchases: '/notas-fiscais', importInvoice: '/notas-fiscais/importar',
  invoice: (value: number) => `/notas-fiscais/${id(value)}`,
  devices: '/dispositivos', registerDevice: '/dispositivos/registrar',
  device: (value: string) => `/dispositivos/${id(value)}`,
  documents: '/documentos',
  document: (value: string) => `/documentos/${id(value)}`,
  versions: (value: string) => `/documentos/${id(value)}/versoes`,
  signers: (value: string) => `/documentos/${id(value)}/signatarios`,
  signer: (document: string, signer: string) => `/documentos/${id(document)}/signatarios/${id(signer)}`,
  downloadUrl: (value: string) => `/documentos/${id(value)}/url-temporaria`,
  startSignature: (value: string) => `/documentos/${id(value)}/sessao-assinatura`,
  consent: (value: string) => `/sessoes-assinatura/${id(value)}/consentimento`,
  biometric: (value: string) => `/sessoes-assinatura/${id(value)}/biometrica`,
  handwritten: (value: string) => `/sessoes-assinatura/${id(value)}/manuscrita`,
  verify: (value: string) => `/assinaturas/verificar/${id(value)}`,
} as const;
